name: Workflow 4
on:
  workflow_run:
    workflows: ["Workflow 3"]
    types:
      - completed
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Show message
        run: echo "Workflow 4 running after Workflow 3"