name: Workflow 3

on:
  workflow_run:
    workflows: ["main"]
    types:
      - completed

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Build
        run: npm run build

      - name: Run Unit Test
        run: npm test