name: Workflow 3
on:
  workflow_run:
    workflows: ["main"]
    types:
      - completed
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Show message
        run: echo "Workflow 3 running after Workflow 1"